In [16]:
import pandas as pd
from sklearn import linear_model
import pickle
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import train_test_split

# Car Sales - Linear Regression

In [17]:
data = pd.read_csv('Car_Price_Data.csv')
model=linear_model.LinearRegression()
model.fit(data[['Mileage','Age']],data[['Sell_Price']])

LinearRegression()

In [18]:
output=model.predict([[44000,12]])

In [19]:
output[0][0]

30451.77773480026

In [20]:
with open("model_car_sale_price_prediction_regression.pkl","wb") as f:
    pickle.dump(model,f)

In [21]:
#Testing Model

In [22]:
with open("model_car_sale_price_prediction_regression","rb") as f:
    mp_car=pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'model_car_sale_price_prediction_regression'

In [23]:
mp_car.predict([[3434,11]])

array([[45502.98331281]])

In [ ]:
mp_car.

In [39]:
mp_car.singular_

array([6.64610935e+04, 6.54005880e-01])

# Iris Data - Classification Model

In [23]:
iris = load_iris()
 
X = iris.data
y = iris.target
 
# Split dataset into train and test
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size = 0.3,
                        random_state = 2018)
 
# import KNeighborsClassifier model
knn = KNN(n_neighbors = 3)
 
# train model
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [24]:
with open("model_iris_classification.pkl","wb") as f:
    pickle.dump(knn,f)

In [25]:
#Testing Model

In [27]:
with open("model_iris_classification.pkl","rb") as f:
    mp_iris=pickle.load(f)

In [30]:
mp_iris

KNeighborsClassifier(n_neighbors=3)

In [78]:
#the loaded model to make predictions
mp_iris.predict([[5.4, 3.4, 1.7, 0.2],
       [5.5, 2.3, 4. , 0],
       [5.6, 3. , 4.5, 1.5]])

array([0, 1, 1])

In [39]:
x1 = 3.1
x2 = 1
x3 = 4
x4 = 0.2
prediction = mp_iris.predict([[x1,x2,x3,x4]])

In [41]:
print(prediction[0])




1


In [35]:
x1='21'
x2='22'

a=x1+x2

In [37]:
x1=float(x1)
x2=float(x2)

b=x1+x2

In [38]:
b

43.0

In [42]:
!pip install json

ERROR: Could not find a version that satisfies the requirement json
ERROR: No matching distribution found for json


In [45]:
!pip install numpy